name: "CI"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  secret_test:
    runs-on: ubuntu-latest
    steps:
    - run: |
        # {
        #   "field1": "value1",
        #   "field2": true,
        #   "field3": {
        #     "subfield": "subfield works",
        #     "floats": 1.234
        #   }
        # }
        echo "Whole JSON: ${{ secrets.MULTIFIELD_JSON }}"
        echo "field1: ${{ secrets.field1 }}"
        echo "field2: ${{ secrets.field2 }}"
        echo "field3: ${{ secrets.field3 }}"
        echo "subfield: ${{ secrets.field3.subfield }}"
        echo "floats: ${{ secrets.field3.floats }}"
  # unit tests
  units:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: action/
    steps:
    - uses: actions/checkout@v3
    - run: npm ci
    - run: npm test

  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./
      with:
        github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
